### ISSUE TITLE
TypeError: Cannot read property 'X_ScreenState' of undefined

### ISSUE THREAD

**Issue by klnspdr** [g30r93g/homebridge-panasonic#23] opened 2019-08-29 19:55 UTC
I'm trying to use the plugin with a TXPW46GW30. When I add the accessory in the Homebridge config and start Homebridge, everything works fine and the TV is shown in HomeKit. But the TV is marked as "no answer", even when the TV is turned on. Then Homebridge crashes.
In the log there is the following message shown:
<img width="1230" alt="Error Message" src="https://user-images.githubusercontent.com/49797464/63971769-98000c80-caa7-11e9-9faf-7bb7848b77b6.png">

**Comment by g30r93g** [comment] 2019-08-30 08:12
Hi there.
Are you sure the TV supports power on from standby?
If you install the Panasonic TV Remote on your phone (ideally v2) can you turn the TV on and off?

**Comment by cmicali** [comment] 2019-10-27 18:44
I am getting the same issue on a TC-P55ST30. All remote control is enabled and manually trying commands with viera.js from the node repl seem to work fine.

**Comment by g30r93g** [comment] 2019-11-03 19:45
Duplicate of #10

**Closed as completed** 2019-11-03 19:45 UTC

**Comment by g30r93g** [comment] 2020-03-23 17:31
Continue discussion in #32
