### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xeronex** [g30r93g/homebridge-panasonic#29] opened 2019-12-10 19:10 UTC
I get this error anyone know why it may be? 

ypeError: properties.find is not a function
    at Subscription.powerStateSubscription.on (/usr/lib/node_modules/homebridge-panasonic-viera-tv/index.js:288:38)
    at emitOne (events.js:116:13)
    at Subscription.emit (events.js:211:7)
    at xmlResponseParser (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/node-upnp-subscription/index.js:37:37)
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:306:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:264:26)
    at emit (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:629:5)
[2019-12-10 18:20:53] Got SIGTERM, shutting down Homebridge...
pi@raspberrypi:~ $

**Comment by g30r93g** [comment] 2020-03-23 17:43
Hi there @xeronex. Thanks for bringing this to my attention. This occurs on occasion when Homebridge polls the TV to get the power state via UPnP subscription. I have a bit more time to look into issues like this so hopefully I will be able to sort this for you.

**Comment by g30r93g** [comment] 2020-03-23 17:48
Duplicate of #22

**Comment by g30r93g** [comment] 2020-03-23 17:49
Please can you continue discussing any issues you encounter regarding this in issue #22

**Closed as completed by g30r93g** 2020-03-23 17:49 UTC

**Comment by g30r93g** [comment] 2020-05-10 11:51
Hopefully v7.1.1 fixes this. If not, please comment in #37
